# 域名地址
baseURL = "https://spacding.github.io"
# 网站语言代码
languageCode = "zh-CN"
# 网站标题
title = "Aseity Life"
# 网站主题
theme = "Ivy"
# 网站logo
avatar = "/static/avatar.png"  # 这里是你的avatar图片文件的路径

disqusShortname = "Aseity"
hasCJKLanguage = true
enableEmoji = true
footnotereturnlinkcontents = "↩"

[permalinks]
  posts = "/posts/:year/:month/:slug/"
  newsletter = "/newsletter/:year/:month/:slug/"

# 菜单参数，通过.Site.Menus.main获取参数
# Name为菜单名称、Weight为菜单排序参数、URL为菜单
[menu]
  [[menu.main]]
  name="文章"
  url="/posts/"
  weight="1"
  [[menu.main]]
  name="电影"
  url="/movies/"
  weight="2"
  [[menu.main]]
  name="阅读"
  url="/books/"
  weight="3"
  [[menu.main]]
  name="书目"
  url="/bibliography/"
  weight="4"
  [[menu.main]]
  name="关于"
  url="/about/"
  weight="5"

# 自定义参数
[params]
  # 网站描述
  description = "人这一生，抛去自己的喜乐悲愁，最终还是要归于尘土，所留下的，无非就是一个或长或短的故事而已。"
  # 页脚
  footer = "&copy; [Aseity](https://blog.aseity.me) | since 2020"
  # 
  highlightjsCDN = "//cdn.bootcss.com"
  # 
  highlightjsLang = ["r", "yaml", "tex"]
  # 
  highlightjsTheme = "github"
  # 
  highlightjsVersion = "9.12.0"

[params.twikoo]
	enable = true

[blackfriday]
extensionsmask = [ "noIntraEmphasis" ]
fractions = false

[markup.highlight]
codeFences = false

[markup.goldmark.renderer]
unsafe = true

[markup.goldmark.parser]
autoHeadingIDType = "blackfriday"

[markup.tableOfContents]
startLevel = 1